config/routes.rb
require 'sidekiq/web'
require 'subdomain'
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin'

  constraints(Subdomain) do
    devise_for :doctors, controllers: {sessions: "doctor/sessions"}, :skip => [:registrations]
    as :doctor do
      get 'doctors/edit' => 'devise/registrations#edit', :as => 'edit_doctor_registration'    
      put 'doctors' => 'devise/registrations#update', :as => 'doctor_registration'            
    end
    devise_for :patients, controllers: {registrations: "patient/patients", sessions: "patient/sessions", confirmations: 'patient/confirmations'}

    authenticate :doctor, lambda { |u| u.role.include?("super_administrator")} do
      mount Sidekiq::Web => '/sidekiq'
    end 

    authenticated :doctor do
      root 'doctor/dashboards#index', as: :doctor_dashboards
      resources "dashboards", module: 'doctor' do       
       post :profile_update, on: :collection
       put :password_update, on: :collection
       get :background_update, on: :collection
       post :address, on: :collection       
       get :order_audits,on: :member
       get :exam_audits,on: :member
       post :card_verification,on: :collection
       get :email_prescription,on: :member
       get :confirm_account, on: :member
       get :reconfirm_notify ,on: :member
       #patient profile actions
       post :new_payment_profile, on: :collection
       post :payment_method_update, on: :collection
       get :account_section, on: :collection
       get :remove_card, on: :collection
       patch :update_patient,on: :member
       put :patient_password_update, on: :collection
       get :todays_appointments,on: :collection
       get :exam_section,on: :collection
       get :order_section,on: :collection
       get :follow_section,on: :collection
       get :dispense_section,on: :collection
      end 

      resources 'examinations', module: 'doctor' do 
        get :view, on: :member
        patch :upload_file, on: :member
        get :download_file, on: :collection
        put :update_medical_rx,on: :member
        get :delete_file, on: :collection
        get :remove_medical_rx, on: :collection
        resources 'referrals' do
          get :send_mail_to_patient, on: :member
          get :find_contact, on: :collection
        end
        resources "manage", controller: 'manage_examination' do
          get :delete_impression, on: :member
          get :delete_procedure, on: :member
          get :medical_history, on: :collection
          get :primilary_binocular, on: :collection
          get :refraction_contact_lens, on: :collection
          get :external_internal, on: :collection
          get :procedure_impression, on: :collection
          get :finalized_prescriptions, on: :collection
          get :attached_docs, on: :collection
          delete :remove_glass_prescription, on: :collection
          delete :remove_lens_prescription, on: :collection 
          delete :remove_lens, on: :collection
          delete :remove_glass, on: :collection         
        end
      end
      get 'doctor/patient/profile' => 'doctor/dashboards#customer_profile'
      get 'doctor/patient/logs' => 'doctor/dashboards#patient_log'
      #get 'doctor/patient/search' => 'doctor/dashboards#search'
      get 'doctor/patient/info' => 'doctor/dashboards#patient_info'
      get '/doctor/patient/:id' => 'patient/dashboards#edit' ,as: 'patient_edit'
      #get '/examination/:id/audits' => 'doctor/dashboards#',as: 'exam_audits'
      resources 'contact_lens_exam', module: 'doctor'
      resources 'dispense_logs',module: 'doctor' do
        get :all_logs,on: :collection
        get :add_new,on: :collection
        get :email_order_ready,on: :collection
      end
      resources :follow_ups,module: 'doctor' do
        get :contact_days,on: :collection
      end
      match 'examination/:examination_id/jr/:id/orders/new', to: "doctor/orders#new",via: [:get,:post], as: :new_order_for_exam
      match 'order/:order_id/jr/:id/examinations/new', to: "doctor/examinations#new",via: [:get,:post], as: :new_exam_for_order
      resources 'orders',module: 'doctor' do
        get :complete_options, on: :member
        get :reload_procedures,on: :member
        patch :add_procedures, on: :member
        delete :delete_procedures, on: :member
        #get :add_contact_lens, on: :collection
        #get :add_eyeglass,on: :collection
        #post :update_new_lens, on: :collection
        #post :update_glass, on: :collection
        #get :eyeglass_suborder, on: :collection
        #get :lens_suborder, on: :collection
        get :lens_prescriptions,on: :collection
        get :lens_prices_base_curves,on: :collection
        get :glass_prescriptions,on: :collection
        get :glass_price,on: :collection
        get :lens_addons_price,on: :collection
        get :glass_frame_price,on: :collection
        get :lens_material_price,on: :collection
        get :lab_order,on: :member
        get :invoice,on: :member
        get :checklist,on: :member
        post :update_checklist,on: :member
        get :dispense,on: :member
        get :email_invoice,on: :member
        get :email_card_warning,on: :member
        #get :glass_order_prescription,on: :collection
        #get :lens_order_prescription,on: :collection
        #get :all_suborders,on: :member
        #new order form actions
        put :refund_amount, on: :member
        get :create_glass_suborder, on: :member
        get :add_glass_addon, on: :member
        get :delete_glass_addon, on: :member
        get :delete_eyeglass_suborder, on: :member
        put :update_eyeglass_suborder, on: :member
        put :update_contact_lens_suborder, on: :member
        get :create_contact_lens_suborder, on: :member
        delete :delete_contact_lens_suborder, on: :member
        get :reload_removed_lens, on: :member
        put :calculate_lens_subtotal, on: :member
        put :calculate_glass_subtotal, on: :member
        get :show_lens_suborder, on: :member
        get :show_glass_suborder, on: :member
        get :reload_updated_lens, on: :member
        get :reload_updated_glass, on: :member
        put :hold_lens_suborder, on: :member
        put :hold_glass_suborder, on: :member
        get :holded_lens_suborder, on: :member
        get :holded_glass_suborder, on: :member
        get :reload_removed_glass, on: :member
        #users listing
        get :online_users,on: :collection
      end
      
      resources 'manage_patients', module: 'doctor', as: 'manage_patients_by_doctor' do
        get :patients_status, on: :collection
        get :todays_appointments,on: :collection
        # get :exam_procedures,on: :collection
        # put :exam_procedure_update,on: :collection
        #get :process_booking, on: :member         #this route is not in use 
      end
      
      resources 'manage_organisations', module: 'doctor' do
        delete :remove_pending_org, on: :collection
      end

      resources 'analytics', module: 'doctor' do
        get :filter, on: :collection
        get :orders_detail, on: :collection
      end

      resources 'setting_patients', module: 'doctor', only: [:index,:update] do        
        post :add_vision_insurance, on: :collection
        post :add_medical_insurance, on: :collection
        get :update_vision_insurance, on: :collection
        get :update_medical_insurance, on: :collection
        delete :delete_vision_insurance, on: :collection
        delete :delete_medical_insurance, on: :collection
        put :upload_file, on: :member
        delete :delete_file, on: :collection
      end

      resources 'setting_schedulers', module: 'doctor', only: [:index] do
        post :add_holiday, on: :collection
        delete :delete_holiday, on: :collection
        post :update_working_schedule, on: :collection
        get :working_schedule, on: :collection
        get :doctor_leave_closure, on: :collection
      end

      resources 'setting_orders', module: 'doctor', only: [:index, :update] do
        post :add_eyeglass_lens_type, on: :collection
        delete :delete_eyeglass_lens_type, on: :collection

        post :add_eyeglass_lens_material, on: :collection
        delete :delete_eyeglass_lens_material, on: :collection

        post :add_eyeglass_addon, on: :collection
        delete :delete_eyeglass_addon, on: :collection

        post :add_eyeglass_frame, on: :collection
        delete :delete_eyeglass_frame, on: :collection

        get :edit_records, on: :collection
        post :update_records, on: :collection
      end

      resources 'settings', module: 'doctor', only: [:index, :update] do 
        post :add_disease, on: :collection
        delete :delete_disease, on: :collection

        post :add_procedure, on: :collection
        delete :delete_procedure, on: :collection

        post :add_lens, on: :collection
        delete :delete_lens, on: :collection

        post :add_impression, on: :collection
        delete :delete_impression, on: :collection

        post :add_recommendation, on: :collection
        delete :delete_recommendation, on: :collection

        get :edit_records, on: :collection
        post :update_records, on: :collection

        get :update_procedure_order, on: :collection
        get :update_recommendation_order, on: :collection

        put :set_default_expiry, on: :member
        put :set_default_escribe_expiry, on: :member

        post :add_exam_cleaning_solution, on: :collection
        delete :delete_cleaning_solution, on: :collection

        put :set_defaut_slot_time, on: :member

        get :exam_form_defaults, on: :collection

        post :set_preliminaries_defaults, on: :collection

        post :set_binocular_defaults, on: :collection

        post :set_external_defaults, on: :collection

        post :set_internal_defaults, on: :collection
      end

      resources "bookings", module: "doctor"  do        
        get :calendar, on: :collection

app/models/eye_glass_order.rb
##
# EyeGlassOrder model values are part of order form.There can be multiple eye glass orders for an order.
# This model value changes is recorded as its audits.

class EyeGlassOrder < ActiveRecord::Base
  
  include CommonSuborder

  before_create :add_organisation_id

  belongs_to :order
  belongs_to :organisation
  belongs_to :eyeglass_types_price
  belongs_to :glass_frames_price
  belongs_to :lens_material
  belongs_to :doctor

  has_many :glasses, dependent: :destroy
  has_many :addon_details, dependent: :destroy

  accepts_nested_attributes_for :glasses,reject_if: :all_blank
  accepts_nested_attributes_for :addon_details,:allow_destroy => true,reject_if: :all_blank
  
  audited :associated_with => :order
 
  acts_as_paranoid
  
  def checklist
    {
      :od_checkmark => self.od_checkmark,
      :os_checkmark => self.os_checkmark,
      :order_checkmark => self.order_checkmark,
      :lens_material_checkmark => self.lens_material_checkmark,
      :eye_glass_type_checkmark => self.eye_glass_type_checkmark,
      :frame_checkmark => self.frame_checkmark
    }
  end
  
  def is_empty_frame_details?
    whitelist = %w[ model eye_size bridge glass_b glass_ed color material temple comments]
    self.attributes.all? do |attr, val|
      whitelist.exclude?(attr) || val.nil? || val == ""
    end
  end

  def overall_discount
    (frame_allowance + (overage_discount/100 * total) + (discount/100 * total)).round(2)
  end

  def calculate_total
    suborder = self
    glass_type_price = suborder.glass_type_price || suborder.try(:eyeglass_types_price).try(:price).to_f
    glass_lens_material = suborder.lens_material_price || suborder.try(:lens_material).try(:price).to_f
    unless frame_price.present?
      frame_x = (suborder.try(:glass_frames_price).try(:price).to_f > suborder.frame_allowance.to_f) ? (suborder.try(:glass_frames_price).try(:price).to_f - suborder.frame_allowance.to_f) : suborder.try(:glass_frames_price).try(:price).to_f        # here we are initializing frame total price based on allowance 
    else
      frame_x = (suborder.frame_price > suborder.frame_allowance.to_f) ? (suborder.frame_price - suborder.frame_allowance.to_f) : suborder.frame_price        # here we are initializing frame total price based on allowance 
    end
    suborder.frame_price = suborder.overage_discount.to_f.between?(0,100) ? (frame_x - (suborder.overage_discount.to_f  * (frame_x/100))) : (suborder.overage_discount = 0)
    suborder.overage_discount,suborder.frame_price = 0,0 if (frame_x - (suborder.overage_discount.to_f  * (frame_x/100))) <= 0
    glass_frame_price = suborder.frame_price || suborder.try(:glass_frames_price).try(:price).to_f               #first checking, if glass order frame price is having any value then place it as it is and if not then place actualy frame price value
    addons_price = suborder.addons_price || suborder.try(:addon_details).map{|add_on| add_on.try(:glass_addons_price).try(:price).to_f}.sum
    subtotal = glass_type_price + addons_price + glass_frame_price + suborder.material_copay.to_f + glass_lens_material
    total =  subtotal - (  suborder.discount.to_f * (subtotal/100))
    self.total = total
    self.save
    self.total
  end

  private
    def add_organisation_id
      self.organisation_id = Organisation.current.try(:id) || 1 unless self.organisation_id.present?
    end

end

app/views/doctor/orders/order_partial/eye_glass_order/_addon_detail_fields.html.haml
= f.simple_fields_for :addon_details, include_id: false do |addon_detail|
  .nested-fields{:id => "glass_addon_"+addon_detail.object.id.to_s }
    .row
      .col-md-4
      .col-md-3
        %label Color
    .row
      .col-md-4
        = addon_detail.input :id, as: :hidden
        = addon_detail.input :glass_addons_price_id, as: :select,collection: current_organisation.glass_addons_prices, :prompt => "Choose a Addon", :label => false,:label_method=> :addon,:value_method=> :id,input_html:{:multiple => false ,:class => "multi-select-addons"}
      .col-md-3
        = addon_detail.input :color,label: false,input_html: {:class => "addon_color"}
      .col-md-2
        .form-group
          .input-group-addon
            %i.fa.fa-dollar.pull-left
            %label{:class => "addon_static_price",:data => { :price => addon_detail.object.new_record? ? "0.00" : addon_detail.object.try(:glass_addons_price).try(:price) },:style => 'display: block;'}
              = addon_detail.object.new_record? ? "0.00" : addon_detail.object.try(:glass_addons_price).try(:price) || "0.00"
      .col-md-2
        -#= link_to_remove_association "<i class=icon-trash icon-white></i>".html_safe, f,data: {confirm: 'Are you sure?'},:class => "addons-price glass_total_calc_for_addons", data: { :suborder => f.object.id }
        = link_to "Remove", delete_glass_addon_order_path(addon_detail.object), remote: true, class: 'btn btn-sm btn-danger'

app/views/doctor/orders/order_partial/eye_glass_order/_eye_glass_order_fields.html.haml
.nested-fields
  .row
    .col-lg-12
      .portlet.box.blue-hoki
        .portlet-title
          .caption
            %i.icon-eyeglasses
            EyeGlasses
            %span.semi-bold Order ##{f.object.id}
          .tools-dropdown-on-portlet.pull-right
            .actions
              = link_to '&nbsp; Hold'.html_safe, hold_glass_suborder_order_path(f.object), :method => :put, :remote => true , :id => 'glass_order_hold_'+f.object.id.to_s,:class => f.object.hold? ? "hold_glass fa fa-gavel icon-white btn btn-sm btn-success" : "hold_glass fa fa-gavel icon-white btn btn-sm blue-hoki"
              - if @order.joint_resource.examinations.present?
                = link_to '&nbsp;Final Rxs'.html_safe,glass_prescriptions_orders_path(:jr_id => @order.joint_resource,:form_id => f.options[:html][:id] ),:remote => true,:data => {:toggle => 'modal', :target => "#prescription"},:class => "fa fa-wrench icon-white btn blue-hoki btn-sm other_prescriptation",:title => 'Other Prescriptions', :rel=> 'tooltip'
              %button.bt_lab_confirm.fa.fa-file-pdf-o{"data-target" => "#input_lab_order_details_"+f.object.id.to_s, "data-toggle" => "modal", :type => "button"} Lab Order
              = link_to '&nbsp;Manually Change'.html_safe,"#glass_manual_toggle_"+f.object.id.to_s,:class => 'fa fa-gear btn btn-sm blue-hoki glass_manual_change ',data: {:suborder => f.object.id}
              = link_to '&nbsp;Remove'.html_safe, delete_eyeglass_suborder_order_path(f.object.id), :remote => true , :class => "fa fa-trash-o icon-white btn blue-hoki btn-sm glass_delete"
              = f.input :doctor_id, as: :hidden,input_html: { value: current_doctor.try(:id) }
        .portlet-body.form
          .form-body
            = f.simple_fields_for :glasses do |glass|
              = glass.input :id, as: :hidden
              .glass_form_fields{:style => 'display:none;',id: "glass_edit_manual_change_"+f.object.id.to_s}
                = render 'doctor/orders/order_partial/eye_glass_order/glass_fields',:f => f,:glass => glass
              .glass_prescription{:id => 'glasses_prescription_manual_change_'+f.object.id.to_s,:style => 'display:block;'}
                = render 'doctor/orders/order_partial/eye_glass_order/glasses_prescription',:suborder => f.object,:glass => glass.object
              = render 'doctor/orders/order_partial/eye_glass_order/glass_benefits',:f => f
              .row
                .col-md-6
                .col-md-6{:style => 'display:none;',id: "glass_save_manual_change_"+f.object.id.to_s}
                  = f.submit 'Save', class: 'pull-right fa fa-floppy-o btn btn-md green glass_save',:"data-no-turbolink"=> "true"

/ Modal for Lab Confirmation over Order Tab Under Eyeglass Order creation.
.modal.fade{:role => "dialog", id: "input_lab_order_details_"+f.object.id.to_s}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Lab Order Confirmation

      .modal-body
        = f.simple_fields_for :glasses do |glass|
          %label.control-label 
            %b Account Number
          =f.input :acc_no,label: false
          %label.control-label 
            %b Message to Lab
          =f.input :msg_lab,label: false
          %b Mark as Urgent
          = f.input :check_box_mark_urgent,label: false, as: :radio_buttons

      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button", class: "btn"} Close
        =f.submit "Next",name: "lab_next",value: "Next", :"data-modal-id" => "#input_lab_order_details_"+f.object.id.to_s, class: "btn green btn_lab_confirm"


/ Modal for Lab Pdf view after Lab Order Confirmation.
.modal.fade{:role => "dialog", id: "view_pdf_modal_"+f.object.id.to_s}
  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title Lab Order Pdf
      .modal-body
        %label View your Lab Order
        = link_to "<i class='fa fa-file-pdf-o'></i>&nbsp;Lab Order".html_safe,lab_order_order_path(f.object,:format => :pdf),:target => '_blank',:onclick => '$(this).closest("form").ajaxSubmit({dataType: "json"})',class: "btn blue-hoki btn-sm" if f.object.id.present?
                
      .modal-footer
        %button.btn.green{:type => "button",:onclick => '$("#input_lab_order_details_'+f.object.id.to_s+'").modal("show");$("#view_pdf_modal_'+f.object.id.to_s+'").modal("hide");'} Back 
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

:javascript
  $('.btn_lab_confirm').on('click',function() {
    $($(this).attr("data-modal-id")).modal('hide');
  })
  
:css
  .bt_lab_confirm
  {
    background-color: Transparent;
    background-repeat: no-repeat;
    border: none;
    cursor: pointer;
    overflow: hidden;
  }

app/views/doctor/orders/order_partial/eye_glass_order/_glass_benefits.html.haml
.portlet.box.red-intense
  .portlet-title{:style => "padding-top: 5px !important; padding-bottom: 0px !important;"}
    .caption
      %i.fa.fa-money
      Benefits
  .portlet-body.form
    .form-body
      .row
        .form-group
          %label.control-label.col-md-3 Material Copay
          .col-md-3
            .input-icon
              %i.fa.fa-dollar
              = f.input :material_copay, label: false,as: :string,:input_html => {value: (number_with_precision(f.object.material_copay, :precision => 2)) ,:class => "glass_total_calc price_inp", data: { :suborder => f.object.id }},:wrapper => false
          %label.control-label.col-md-3 Frame Allowance
          .col-md-3
            .input-icon
              %i.fa.fa-dollar
              = f.input :frame_allowance, label: false,as: :string,:input_html => {value: (number_with_precision(f.object.frame_allowance, :precision => 2)) ,:class => "glass_total_calc price_inp input-icon", data: { :suborder => f.object.id }},:wrapper => false
      .row
        .form-group
          %label.control-label.col-md-3 Frame Only Discount
          .col-md-3
            %i.percent_icon %
            = f.input :overage_discount, label: false,as: :string,:input_html => {value: (number_with_precision(f.object.overage_discount, :precision => 2)) ,:class => "glass_total_calc price_inp percent_box", data: { :suborder => f.object.id }},:wrapper => false
          %label.control-label.col-md-3 Overall Discount(%)
          .col-md-3
            %i.percent_icon %
            = f.input :discount, label: false,as: :string,:input_html => {value: (number_with_precision(f.object.discount, :precision => 2)) ,:class => 'price_inp glass_total_calc percent_box', data: { :suborder => f.object.id }},:wrapper => false
      .row
        .form-group
          %label.control-label.col-md-6
            .well
              .goods-page-price
                %strong Total
              .form-group
                .input-icon
                  %i.fa.fa-dollar
                  = f.input :total, label: false,as: :string,:input_html => {value: (number_with_precision(f.object.total, :precision => 2)) ,:class => 'eye_glass_order_total price_inp'},:wrapper => false
          .col-md-6
            = f.input :comments, as: :text,:input_html => {:cols => 6, :rows => 3 }

app/views/doctor/orders/order_partial/eye_glass_order/_glass_order.html.haml
= f.simple_fields_for :eye_glass_orders,@order.eye_glass_orders do |glass_order|
  = render 'doctor/orders/order_partial/eye_glass_order/eye_glass_order_fields',:f => glass_order,:sherlock => glass_order.options[:child_index]
.pull-right 
  = link_to_add_association "<i class='fa fa-plus'></i>&nbsp;Add new".html_safe, f, :eye_glass_orders,:partial => 'doctor/orders/order_partial/eye_glass_order/eye_glass_order_fields',:render_options => {:locals => {:sherlock => Time.now.to_i }},:class => "btn btn-success lens-tools tooltip-set","data-original-title" => "click to add more eye glass orders", "data-placement" => "right", "data-toggle" => "tooltip"

app/views/doctor/orders/order_partial/eye_glass_order/_glass_prescriptions.html.haml
.row
  - if object.any?
    - object.each_with_index do |ord,index|
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th
              #{index+1}.
            %td
              %b
                Issue date:
              = ord['issued_date']
            %th.hidden-480
              SPHERE
            %th.hidden-480
              CYLINDER
            %th.hidden-480
              AXIS
            %th.hidden-480
              ADD
            %th.hidden-480
              PRISM
        %tbody
          .col-md-12
            %tr
              %th
              %th
                OD
              %td
                = ord['od_sphere']
              %td.hidden-480
                = ord['od_cylinder']
              %td.hidden-480
                = ord['od_axis']
              %td.hidden-480
                = ord['ou_add']
              %td.hidden-480
                = ord['od_prism']
          .col-md-12
            %tr
              %th
              %th
                OS
              %td
                = ord['os_sphere']
              %td.hidden-480
                = ord['os_cylinder']
              %td.hidden-480
                = ord['os_axis']
              %td.hidden-480
                = ord['ou_add']
              %td.hidden-480
                = ord['os_prism']
              
          .col-md-12
            %tr
              %th
              %th
                Recommendations:
              %td{:colspan => "5"}
                = ord['doctor_recommendations'].is_a?(Array) ? ord['doctor_recommendations'].compact.join(', ') : ord['doctor_recommendations']
          .col-md-12
            %tr
              %th
              %th
                Comments
              %td{:colspan => "4"}
                = ord['comments'].is_a?(Array) ? ord['comments'].compact.join(', ') : ord['comments']
              %td.hidden-480
                %button{:href => "#",:class => "select_glass_prescp_option btn btn-primary pull-right" ,:data => {:dismiss => 'modal',:form_prescp => form_id,:selected => ord }}Import
              
  - else
    .col-md-8.text-center
      %i.fa.fa-search
      %em No prescription found
:javascript
  $(document).on('click','.select_glass_prescp_option',function(){
    var form = $('#'+$(this).data('form-prescp'));
    form.find('#eye_glass_order_glasses_attributes_0_od_sphere').val($(this).data('selected-od-sphere'));

    form.find('#eye_glass_order_glasses_attributes_0_od_cylinder').val($(this).data('selected-od-cylinder'));
    
    form.find('#eye_glass_order_glasses_attributes_0_od_axis').val($(this).data('selected-od-axis'));

    form.find('#eye_glass_order_glasses_attributes_0_od_prism').val($(this).data('selected-od-prism'));
    
    form.find('#eye_glass_order_glasses_attributes_0_ou_add').val($(this).data('selected-ou-add'));
    
    form.find('#eye_glass_order_glasses_attributes_0_os_sphere').val($(this).data('selected-os-sphere'));
    
    form.find('#eye_glass_order_glasses_attributes_0_os_cylinder').val($(this).data('selected-os-cylinder'));
    
    form.find('#eye_glass_order_glasses_attributes_0_os_axis').val($(this).data('selected-os-axis'));
    
    form.find('#eye_glass_order_glasses_attributes_0_os_prism').val($(this).data('selected-os-prism'));

    if(!isNaN($(this).data('selected-finalize'))){
      form.find('#eye_glass_order_glasses_attributes_0_selected_finalize').val("true");
    }

    // To toggle static prescription view on importing a prescription
    // if(form.find('.glass_form_fields').is(':hidden')){
      //form.find('.lens_manual_change').trigger('click');
      $('#glass_edit_manual_change_'+$(this).data('form-prescp').match(/\d+/)[0]+",#glasses_prescription_manual_change_"+$(this).data('form-prescp').match(/\d+/)[0]+",#glass_save_manual_change_"+$(this).data('form-prescp').match(/\d+/)[0]);
    // }
    form.submit();
  });