config/routes.rb
require 'sidekiq/web'
require 'subdomain'
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin'

  constraints(Subdomain) do
    devise_for :doctors, controllers: {sessions: "doctor/sessions"}, :skip => [:registrations]
    as :doctor do
      get 'doctors/edit' => 'devise/registrations#edit', :as => 'edit_doctor_registration'    
      put 'doctors' => 'devise/registrations#update', :as => 'doctor_registration'            
    end
    devise_for :patients, controllers: {registrations: "patient/patients", sessions: "patient/sessions", confirmations: 'patient/confirmations'}

    authenticate :doctor, lambda { |u| u.role.include?("super_administrator")} do
      mount Sidekiq::Web => '/sidekiq'
    end 

    authenticated :doctor do
      root 'doctor/dashboards#index', as: :doctor_dashboards
      resources "dashboards", module: 'doctor' do       
       post :profile_update, on: :collection
       put :password_update, on: :collection
       get :background_update, on: :collection
       post :address, on: :collection       
       get :order_audits,on: :member
       get :exam_audits,on: :member
       post :card_verification,on: :collection
       get :email_prescription,on: :member
       get :confirm_account, on: :member
       get :reconfirm_notify ,on: :member
       #patient profile actions
       post :new_payment_profile, on: :collection
       post :payment_method_update, on: :collection
       get :account_section, on: :collection
       get :remove_card, on: :collection
       patch :update_patient,on: :member
       put :patient_password_update, on: :collection
       get :todays_appointments,on: :collection
       get :exam_section,on: :collection
       get :order_section,on: :collection
       get :follow_section,on: :collection
       get :dispense_section,on: :collection
      end 

      resources 'examinations', module: 'doctor' do 
        get :view, on: :member
        patch :upload_file, on: :member
        get :download_file, on: :collection
        put :update_medical_rx,on: :member
        get :delete_file, on: :collection
        get :remove_medical_rx, on: :collection
        resources 'referrals' do
          get :send_mail_to_patient, on: :member
          get :find_contact, on: :collection
        end
        resources "manage", controller: 'manage_examination' do
          get :delete_impression, on: :member
          get :delete_procedure, on: :member
          get :medical_history, on: :collection
          get :primilary_binocular, on: :collection
          get :refraction_contact_lens, on: :collection
          get :external_internal, on: :collection
          get :procedure_impression, on: :collection
          get :finalized_prescriptions, on: :collection
          get :attached_docs, on: :collection
          delete :remove_glass_prescription, on: :collection
          delete :remove_lens_prescription, on: :collection 
          delete :remove_lens, on: :collection
          delete :remove_glass, on: :collection         
        end
      end
      get 'doctor/patient/profile' => 'doctor/dashboards#customer_profile'
      get 'doctor/patient/logs' => 'doctor/dashboards#patient_log'
      #get 'doctor/patient/search' => 'doctor/dashboards#search'
      get 'doctor/patient/info' => 'doctor/dashboards#patient_info'
      get '/doctor/patient/:id' => 'patient/dashboards#edit' ,as: 'patient_edit'
      #get '/examination/:id/audits' => 'doctor/dashboards#',as: 'exam_audits'
      resources 'contact_lens_exam', module: 'doctor'
      resources 'dispense_logs',module: 'doctor' do
        get :all_logs,on: :collection
        get :add_new,on: :collection
        get :email_order_ready,on: :collection
      end
      resources :follow_ups,module: 'doctor' do
        get :contact_days,on: :collection
      end
      match 'examination/:examination_id/jr/:id/orders/new', to: "doctor/orders#new",via: [:get,:post], as: :new_order_for_exam
      match 'order/:order_id/jr/:id/examinations/new', to: "doctor/examinations#new",via: [:get,:post], as: :new_exam_for_order
      resources 'orders',module: 'doctor' do
        get :complete_options, on: :member
        get :reload_procedures,on: :member
        patch :add_procedures, on: :member
        delete :delete_procedures, on: :member
        #get :add_contact_lens, on: :collection
        #get :add_eyeglass,on: :collection
        #post :update_new_lens, on: :collection
        #post :update_glass, on: :collection
        #get :eyeglass_suborder, on: :collection
        #get :lens_suborder, on: :collection
        get :lens_prescriptions,on: :collection
        get :lens_prices_base_curves,on: :collection
        get :glass_prescriptions,on: :collection
        get :glass_price,on: :collection
        get :lens_addons_price,on: :collection
        get :glass_frame_price,on: :collection
        get :lens_material_price,on: :collection
        get :lab_order,on: :member
        get :invoice,on: :member
        get :checklist,on: :member
        post :update_checklist,on: :member
        get :dispense,on: :member
        get :email_invoice,on: :member
        get :email_card_warning,on: :member
        #get :glass_order_prescription,on: :collection
        #get :lens_order_prescription,on: :collection
        #get :all_suborders,on: :member
        #new order form actions
        put :refund_amount, on: :member
        get :create_glass_suborder, on: :member
        get :add_glass_addon, on: :member
        get :delete_glass_addon, on: :member
        get :delete_eyeglass_suborder, on: :member
        put :update_eyeglass_suborder, on: :member
        put :update_contact_lens_suborder, on: :member
        get :create_contact_lens_suborder, on: :member
        delete :delete_contact_lens_suborder, on: :member
        get :reload_removed_lens, on: :member
        put :calculate_lens_subtotal, on: :member
        put :calculate_glass_subtotal, on: :member
        get :show_lens_suborder, on: :member
        get :show_glass_suborder, on: :member
        get :reload_updated_lens, on: :member
        get :reload_updated_glass, on: :member
        put :hold_lens_suborder, on: :member
        put :hold_glass_suborder, on: :member
        get :holded_lens_suborder, on: :member
        get :holded_glass_suborder, on: :member
        get :reload_removed_glass, on: :member
        #users listing
        get :online_users,on: :collection
      end
      
      resources 'manage_patients', module: 'doctor', as: 'manage_patients_by_doctor' do
        get :patients_status, on: :collection
        get :todays_appointments,on: :collection
        # get :exam_procedures,on: :collection
        # put :exam_procedure_update,on: :collection
        #get :process_booking, on: :member         #this route is not in use 
      end
      
      resources 'manage_organisations', module: 'doctor' do
        delete :remove_pending_org, on: :collection
      end

      resources 'analytics', module: 'doctor' do
        get :filter, on: :collection
        get :orders_detail, on: :collection
      end

      resources 'setting_patients', module: 'doctor', only: [:index,:update] do        
        post :add_vision_insurance, on: :collection
        post :add_medical_insurance, on: :collection
        get :update_vision_insurance, on: :collection
        get :update_medical_insurance, on: :collection
        delete :delete_vision_insurance, on: :collection
        delete :delete_medical_insurance, on: :collection
        put :upload_file, on: :member
        delete :delete_file, on: :collection
      end

      resources 'setting_schedulers', module: 'doctor', only: [:index] do
        post :add_holiday, on: :collection
        delete :delete_holiday, on: :collection
        post :update_working_schedule, on: :collection
        get :working_schedule, on: :collection
        get :doctor_leave_closure, on: :collection
      end

      resources 'setting_orders', module: 'doctor', only: [:index, :update] do
        post :add_eyeglass_lens_type, on: :collection
        delete :delete_eyeglass_lens_type, on: :collection

        post :add_eyeglass_lens_material, on: :collection
        delete :delete_eyeglass_lens_material, on: :collection

        post :add_eyeglass_addon, on: :collection
        delete :delete_eyeglass_addon, on: :collection

        post :add_eyeglass_frame, on: :collection
        delete :delete_eyeglass_frame, on: :collection

        get :edit_records, on: :collection
        post :update_records, on: :collection
      end

      resources 'settings', module: 'doctor', only: [:index, :update] do 
        post :add_disease, on: :collection
        delete :delete_disease, on: :collection

        post :add_procedure, on: :collection
        delete :delete_procedure, on: :collection

        post :add_lens, on: :collection
        delete :delete_lens, on: :collection

        post :add_impression, on: :collection
        delete :delete_impression, on: :collection

        post :add_recommendation, on: :collection
        delete :delete_recommendation, on: :collection

        get :edit_records, on: :collection
        post :update_records, on: :collection

        get :update_procedure_order, on: :collection
        get :update_recommendation_order, on: :collection

        put :set_default_expiry, on: :member
        put :set_default_escribe_expiry, on: :member

        post :add_exam_cleaning_solution, on: :collection
        delete :delete_cleaning_solution, on: :collection

        put :set_defaut_slot_time, on: :member

        get :exam_form_defaults, on: :collection

        post :set_preliminaries_defaults, on: :collection

        post :set_binocular_defaults, on: :collection

        post :set_external_defaults, on: :collection

        post :set_internal_defaults, on: :collection
      end

      resources "bookings", module: "doctor"  do        
        get :calendar, on: :collection

app/models/setting.rb
##
# Setting is sore some organisation specific date Like Ranges for various Exam select field. 

class Setting < ActiveRecord::Base
  belongs_to :organisation

  before_create :add_organisation_id

  has_many :documents, dependent: :destroy
  
  
  private
    def add_organisation_id
      self.organisation_id = Organisation.current.try(:id) || 1 unless self.organisation_id.present?
    end
end

app/controllers/doctor/base_controller.rb
##
#  All doctor namespace controller inherited from BaseController

class Doctor::BaseController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "Access denied."
    redirect_to root_url
  end

  def current_ability
    @current_ability ||= Ability.new(current_doctor)
  end
  
end

app/controllers/doctor/contact_lens_distribution_orders_controller.rb
class Doctor::ContactLensDistributionOrdersController < Doctor::BaseController


	def new
		@examination = Examination.find params[:exam]
		@patient_id = @examination.joint_resource.patient_id
		@lens = Lens.find_by(id: params[:lens_id])
		@contact_lens_distributon_order = ContactLensDistributionOrder.new
		respond_to do |format| 
			format.html    { render :index }
			format.js  
		end
	end


	def create
		begin
			if params[:contact_lens_distribution_order].present?
				@contact_lens_distribution_order = ContactLensDistributionOrder.new(params.require(:contact_lens_distribution_order).permit!)
				if @contact_lens_distribution_order.save!
					flash[:status] = "Success"
					flash[:notice] = "Confirmed!"   
				end
			end
		rescue Exception => e
			flash[:status] = 'Error'
			flash[:notice] = "Error due to #{e.message}"
		end
		render :json => {status: flash[:status], msg: flash[:notice]}.to_json
	end

	def edit
		@lens = Lens.find_by(id: params[:lens_id])
		@contact_lens_distributon_order = ContactLensDistributionOrder.find(params[:id])
	end


	def update
		begin
			@contact_lens_distribution_order = ContactLensDistributionOrder.find params[:id]
			@contact_lens_distribution_order.update(params.require(:contact_lens_distribution_order).permit!)
			flash[:status] = "Success"
			flash[:notice] = "Confirmed!"
		rescue Exception => e
			flash[:status] = 'Error'
			flash[:notice] = "Error due to #{e.message}"
		end
		render :json => {status: flash[:status], msg: flash[:notice]}.to_json
	end

	def destroy
		@contact_lens_distribution_order = ContactLensDistributionOrder.find(params[:id]) 
		if @contact_lens_distribution_order.destroy
			@contact_lens_distribution_orders = ContactLensDistributionOrder.all
			flash[:status] = "Success"
			flash[:notice] = "Deleted successfully!"
		end    
		respond_to do |format|
			format.html {redirect_to :back}
			format.json { render :json => {status: flash[:status], msg: flash[:notice]}.to_json }
			format.js
		end
		
	end

	def order_contact
		if params[:id].present?
			@contact = Contact.find params[:id]
		end
		respond_to do |format| 
			format.html
			format.js  
		end
	end

	def send_report
		if params[:contact_emails].present?
			@acount_numbers = []
			acount = params[:contact_acounts].split(",")
			params[:contact_acounts].split(",").each_with_index do |value, index|
				if index.even?
					@acount_numbers	<< [acount[index], acount[index+1]]
				end
			end
			@store = current_doctor.store
			@contact_lens_distribution_orders = @store.contact_lens_distribution_orders.where(soft_delete: false)
			contact_emails = params[:contact_emails].split(",").uniq
			AppMailer.send_order_to_contact(contact_emails, current_doctor, "You have recevied a new contact lens order from #{@store.description}", @acount_numbers).deliver_later

			AppMailer.send_order_to_contact(@store.contact_email, current_doctor, "You have just placed a contact lens order", @acount_numbers).deliver_later
				
			@store.contact_lens_distribution_orders.update_all(soft_delete: true)
			
			@contact_lens_distribution_orders = @store.contact_lens_distribution_orders.where(soft_delete: false)
			respond_to do |format| 
				format.html 
				format.js
			end
		end
	end

	def lens_pdf
		begin
			@contact_lens_distribution_orders = current_doctor.store.contact_lens_distribution_orders
			@doctor = current_doctor
			generate_pdf('/doctor/dashboards/dashboard_partial/contact_lens_pdf.html','trial_lens_order.pdf')
		rescue Exception => e
			flash[:status] = 'Error'
			flash[:notice] = "Error due to #{e.message}"
		end
	end

	private
		def generate_pdf(template_pth,file_name)
        pdf = WickedPdf.new.pdf_from_string(
                                render_to_string(
                                  template: template_pth,
                                  layout: 'layouts/application.pdf.haml'))
        send_data(pdf,
                  filename: file_name,
                  type: 'application/pdf',
                  disposition: 'attachment')
      end

end

app/controllers/doctor/contact_lens_exam_controller.rb
class Doctor::ContactLensExamController < Doctor::BaseController
  def new
    @contact_lens_exam = ContactLensExam.new
    construct_float_dropdown
  end

  def create
    @contact_lens_exam = ContactLensExam.new(contact_lens_exam_params)
    respond_to do |format|
      if @contact_lens_exam.save
        return render :json => {:success => true}
      else
        return render :json => {:success => false, :message => @contact_lens_exam.errors.join(", ")}
      end
    end
  end

  private
  def construct_float_dropdown
    @float_dropdown = []
    $i = 32
    while $i <= 52
      @float_dropdown.push($i)
      $i += 0.25
    end
  end

  def contact_lens_exam_params
    params.require(:contact_lens_exam).permit(:name,
                                              :dob,
                                              :age,
                                              :od_d_h, 
                                              :od_mm_h, 
                                              :od_axis_h, 
                                              :os_d_h, 
                                              :os_d_h, 
                                              :os_mm_h, 
                                              :os_axis_h,
                                              :od_d_v, 
                                              :od_mm_v, 
                                              :od_axis_v, 
                                              :os_d_v, 
                                              :os_d_v, 
                                              :os_mm_v, 
                                              :os_axis_v)
  end 
end

app/controllers/doctor/family_members_controller.rb
##
# FamilyMembers concern have all functionality for this controller

class Doctor::FamilyMembersController <  Doctor::BaseController
	skip_before_action :verify_authenticity_token
	include FamilyMembers
	
end

app/views/doctor/settings/_exam_form_defaults.html.haml
//Preliminaries---------------------------------------------//

.portlet.box
  .portlet-title.hex_424242
    .caption
      %i.fa.fa-plus-square>
      Preliminaries
  .portlet-body
    .row
      = simple_form_for :exam_form_preliminary_defaults , url: set_preliminaries_defaults_settings_path, remote: true do |primlinary_f|
        .col-md-7
          .row
            .col-md-8
              = primlinary_f.input :eoms_def,label: "Eoms" , :input_html => {:value=> @def_values.eoms_def.present? ? @def_values.eoms_def : ""},required: false
          .row
            .col-md-8
              = primlinary_f.input :pupils_def, label: "Pupils" ,:input_html => {:value=> @def_values.pupils_def.present? ? @def_values.pupils_def : ""},required: false
          .row
            .col-md-8
              = primlinary_f.input :steropsis_def, label: "Stereopsis (Randot)", :input_html => {:value=> @def_values.steropsis_def.present? ? @def_values.steropsis_def : ""},required: false
        .col-md-5
          = primlinary_f.input :confrontational_def, label: "Confrontational Field", :input_html => {:value=>  @def_values.confrontational_def.present? ? @def_values.confrontational_def : ""},required: false

          = primlinary_f.input :color_vision_def, label: "Color Vision", :input_html => {:value=>  @def_values.color_vision_def.present? ? @def_values.color_vision_def : ""},required: false

          = primlinary_f.input :prelm_notes_def, label: "Additional testings / Notes", placeholder: "Add Notes", :input_html => {:value=>  @def_values.prelm_notes_def.present? ? @def_values.prelm_notes_def : ""},required: false
        .col-md-2
          = submit_tag "Update" ,class: "btn btn-success"



//Binocular Testing---------------------------------------------//
.portlet.box
  .portlet-title.hex_424242
    .caption
      %i.fa.fa-plus-square>
      Binocular Testing
  .portlet-body
    .row
      = simple_form_for :exam_form_binocular_defaults , url: set_binocular_defaults_settings_path, remote: true do |binocular_f| 
        .col-md-6
          %label
            Cover Test
          .row
            .col-md-4
              = binocular_f.input :ctd_def, label: "Distance", :wrapper_html => { :class => ''}, :input_html => {:value=> @def_values.ctd_def.present? ? @def_values.ctd_def : ""},required: false
  
            .col-md-4
              = binocular_f.input :ctn_def, label: "Near", :input_html => {:value=> @def_values.ctn_def.present? ? @def_values.ctn_def : ""},required: false
          .row
            .col-md-4
              = binocular_f.input :nra_def, label: "NRA", :input_html => {:value=> @def_values.nra_def.present? ? @def_values.nra_def : ""},required: false
            .col-md-4
              = binocular_f.input :pra_def, label: "PRA", :input_html => {:value=> @def_values.pra_def.present? ? @def_values.pra_def : ""},required: false
            .col-md-2
              = binocular_f.input :npc_def, label: "NPC", :input_html => {:value=> @def_values.npc_def.present? ? @def_values.npc_def : ""},required: false
            .row
            .col-md-10
              = binocular_f.input :notes_def, label: false, placeholder: "Add Notes", :input_html => {:value=> @def_values.notes_def.present? ? @def_values.notes_def : ""},required: false
        .col-md-6
          %label
            Phorias
          .row 
            %label.col-md-4
              Horizontal
            .col-md-4
              = binocular_f.input :hpd_def, label: "Distance", :input_html => {:value=> @def_values.hpd_def.present? ? @def_values.hpd_def : ""},required: false
            .col-md-4
              = binocular_f.input :hpn_def, label: "Near", :input_html => {:value=> @def_values.hpn_def.present? ? @def_values.hpn_def : ""},required: false
          .row 
            %label.col-md-4
              Vertical
            .col-md-4
              = binocular_f.input :vpd_def, label: "Distance", class: "col-lg-10", :input_html => {:value=> @def_values.vpd_def.present? ? @def_values.vpd_def : ""},required: false
            .col-md-4
              = binocular_f.input :vpn_def, label: "Near", :input_html => {:value=> @def_values.vpn_def.present? ? @def_values.vpn_def : ""},required: false
            .col-md-2
              = submit_tag "Update" ,class: "btn btn-success"


//External Exam---------------------------------------------//
.portlet.box
  .portlet-title.hex_424242
    .caption
      %i.fa.fa-plus-square>
      External Exam
  .portlet-body
    .row
      = simple_form_for :exam_form_external_defaults , url: set_external_defaults_settings_path, remote: true do |ext_f| 
        .col-md-6
          .row
            .col-md-4
              = ext_f.input :tear_film_def, label: "Tear film", :wrapper_html => { :class => ''}, :input_html => {:value=> @def_values.tear_film_def.present? ? @def_values.tear_film_def : ""},required: false
  
            .col-md-4
              = ext_f.input :cornea_def, label: "Cornea", :input_html => {:value=> @def_values.cornea_def.present? ? @def_values.cornea_def : ""},required: false
          .row
            .col-md-4
              = ext_f.input :lids_lashes_def, label: "Lids lashes", :input_html => {:value=> @def_values.lids_lashes_def.present? ? @def_values.lids_lashes_def : ""},required: false
            .col-md-4
              = ext_f.input :iris_def, label: "Iris", :input_html => {:value=> @def_values.iris_def.present? ? @def_values.iris_def : ""},required: false
          .row
            .col-md-4
              = ext_f.input :lens_def, label: "Lens", :input_html => {:value=> @def_values.lens_def.present? ? @def_values.lens_def : ""},required: false
            .col-md-4
              = ext_f.input :ac_def, label: "Ac", :input_html => {:value=> @def_values.ac_def.present? ? @def_values.ac_def : ""},required: false
          .row
            .col-md-4
              %strong
                Cycloplegic Drop Used:
          %br           
          .row
            .col-md-4
              = ext_f.input :cyclopelgic_text, label: "Drop 1", :input_html => {:value=> @def_values.cyclopelgic_text.present? ? @def_values.cyclopelgic_text: ""},required: false 
            .col-md-4
              = ext_f.input :cyclopelgic1_text, label: "Drop 2", :input_html => {:value=> @def_values.cyclopelgic1_text.present? ? @def_values.cyclopelgic1_text : ""},required: false
          .row
            .col-md-4
              = ext_f.input :cyclopelgic2_text, label: "Drop 3", :input_html => {:value=> @def_values.cyclopelgic2_text.present? ? @def_values.cyclopelgic2_text : ""},required: false 
            .col-md-4
              = ext_f.input :cyclopelgic3_text, label: "Drop 4", :input_html => {:value=> @def_values.cyclopelgic3_text.present? ? @def_values.cyclopelgic3_text : ""},required: false                 
        .col-md-6
          .row 

            .col-md-4
              = ext_f.input :palpebral_conj_def, label: "Palpebral conj", :input_html => {:value=> @def_values.palpebral_conj_def.present? ? @def_values.palpebral_conj_def : ""},required: false
            .col-md-4
              = ext_f.input :sclera_def, label: "Sclera", :input_html => {:value=> @def_values.sclera_def.present? ? @def_values.sclera_def : ""},required: false
          .row  
            .col-md-4
              = ext_f.input :bulbar_conj_def, label: "Bulbar conj", :input_html => {:value=> @def_values.bulbar_conj_def.present? ? @def_values.bulbar_conj_def : ""},required: false
            .col-md-4
              = ext_f.input :visual_field_def, label: "Visual Field", class: "col-lg-10", :input_html => {:value=> @def_values.visual_field_def.present? ? @def_values.visual_field_def : ""},required: false
          .row 

            
          .row  
            %label.col-md-4
              Angles
            .col-md-4
              = ext_f.input :angles_od_def, label: "OD", :input_html => {:value=> @def_values.angles_od_def.present? ? @def_values.angles_od_def : ""},required: false
            .col-md-4
              = ext_f.input :angles_os_def, label: "OS", :input_html => {:value=> @def_values.angles_os_def.present? ? @def_values.angles_os_def : ""},required: false
            .col-md-2
              = submit_tag "Update" ,class: "btn btn-success"

//External Exam---------------------------------------------//
.portlet.box
  .portlet-title.hex_424242
    .caption
      %i.fa.fa-plus-square>
      Internal Exam
  .portlet-body
    .row
      = simple_form_for :exam_form_internal_defaults, url: set_internal_defaults_settings_path, remote: true do |ext_f| 
        .col-md-6
          .row
            .col-md-6
              = ext_f.input :od_def, label: "OD C/D", :wrapper_html => { :class => ''}, :input_html => {:value=> @def_values.od_def.present? ? @def_values.od_def : ""},required: false
  
          .row
            .col-md-6
              = ext_f.input :os_def, label: "OS C/D", :input_html => {:value=> @def_values.os_def.present? ? @def_values.os_def : ""},required: false
            .col-md-8
              = ext_f.input :post_pole_def, label: "Post pole", :input_html => {:value=> @def_values.post_pole_def.present? ? @def_values.post_pole_def : ""},required: false
            
            .col-md-8
              = ext_f.input :periphery_def, label: "Periphery", :input_html => {:value=> @def_values.periphery_def.present? ? @def_values.periphery_def : ""},required: false
            .col-md-10
              = ext_f.input :vitreous_def, label: "Vitreous", :input_html => {:value=> @def_values.vitreous_def.present? ? @def_values.vitreous_def : ""},required: false
        .col-md-6
          .row 
            
            .col-md-8
              = ext_f.input :vessels_def, label: "Vessels", :input_html => {:value=> @def_values.vessels_def.present? ? @def_values.vessels_def : ""},required: false
          .row    
            .col-md-8
              = ext_f.input :macula_def, label: "Macula", :input_html => {:value=> @def_values.macula_def.present? ? @def_values.macula_def : ""},required: false
          .row
            %label.col-md-10
              Dilation
          .row  
            .col-md-10
              = ext_f.input :dilation_fundus_def, label: false, :input_html => {:value=>  @def_values.dilation_fundus_def.present? ? @def_values.dilation_fundus_def : ""},required: false
          %br               
          .row
            .col-md-6
              = ext_f.input :tropicomide, label: "Drop 1", :input_html => {:value=> @def_values.tropicomide.present? ? @def_values.tropicomide : ""},required: false 
            .col-md-6
              = ext_f.input :phenylephrine, label: "Test 1", :input_html => {:value=> @def_values.phenylephrine.present? ? @def_values.phenylephrine : ""},required: false
          .row
            .col-md-6
              = ext_f.input :fundus, label: "Drop 2", :input_html => {:value=> @def_values.fundus.present? ? @def_values.fundus : ""},required: false 
            .col-md-6
              = ext_f.input :ophthalmoscopy, label: "Test 2", :input_html => {:value=> @def_values.ophthalmoscopy.present? ? @def_values.ophthalmoscopy : ""},required: false
          .row
            .col-md-6
              = ext_f.input :drop3_text, label: "Drop 3", :input_html => {:value=> @def_values.drop3_text.present? ? @def_values.drop3_text : ""},required: false
          .row     
            .col-md-6
              = ext_f.input :drop4_text, label: "Drop 4", :input_html => {:value=> @def_values.drop4_text.present? ? @def_values.drop4_text : ""},required: false
                              
            .col-md-10
              = ext_f.input :reason_field_def, label: "Reason", :input_html => {:value=> @def_values.reason_field_def.present? ? @def_values.reason_field_def : ""},required: false
            .col-md-10
              = ext_f.input :dilation_od_def, label: "OD", :input_html => {:value=> @def_values.dilation_od_def.present? ? @def_values.dilation_od_def : ""},required: false
            .col-md-10
              = ext_f.input :dilation_os, label: "OS", :input_html => {:value=> @def_values.dilation_os.present? ? @def_values.dilation_os : ""},required: false
          .row  
            .col-md-2
              = submit_tag "Update" ,class: "btn btn-success"

app/views/doctor/settings/add_impression.js.erb
var item = <%= @data.first.to_json.html_safe %>
$('#Impression_modal').modal('hide');
var changed_object = $("input").filter(function () {
  return this.value === item.label;
});
changed_object.val(item.label)
$('.spinner').show();
var time = (new Date).getTime();
if(item.id!="")
{
  $(changed_object).before('<input class="hidden" type="radio" value="OU" checked="checked" name="examination[exam_impressions_attributes]['+time+'][eye]"><input class="hidden" type="radio" value="OS" name="examination[exam_impressions_attributes]['+time+'][eye]" ><input class="hidden" type="radio" value="OD" name="examination[exam_impressions_attributes]['+time+'][eye]" ><input class="hidden" type="text" value="" name="examination[exam_impressions_attributes]['+time+'][plan]"><input type="hidden" value="'+item.id+'" name="examination[exam_impressions_attributes]['+time+'][impression_id]">')

  $('.spinner').show();
  data = $(".exam-form" ).serialize();
  formSubmit(data);       
  myFirebaseRef.child("procedure_impression_plan_page").transaction(function(data){ return $.now()});
  changed_object.value="";
}
function formSubmit(data)
{
  $.ajax({
    url: $(".exam-form" ).attr("action"),
    type: 'POST',
    data: data,
    async: false
  });
} 

app/views/doctor/settings/edit_records.js.erb
$('#edit_records_body').html("<%= escape_javascript(render partial: 'doctor/settings/forms/'+@partial) %>");

$("#edit_records_modal").modal();

app/views/doctor/settings/exam_form_defaults.js.erb
jQuery.gritter.add({ title: "Success", text: "<%= msg%>" });